### PR TITLE
Add missing whitelabeling support

### PR DESCRIPTION
**Pull request by misaka**
Whitelabeling support was missing from `TaskLiskComponent` and the `visually_hidden` helper.

### CODE REVIEW

**Review by frankieroberto — APPROVED** [review]
Opps, this was my fault.

PR looks good to me, thanks!

**Review by peteryates — APPROVED** [review]

**Comment by peteryates** [comment]
Ah should have noticed - especially as I only recently added the visually hidden helper very recently 🤦🏽

Thanks @misaka ❤️

**Comment by misaka** [comment]
Thanks @peteryates @frankieroberto. Do I need to do anything else to get this PR merged?

**Comment by frankieroberto** [comment]
@misaka I've merged it now. @peteryates should we release this as a patch version?

**Comment by peteryates** [comment]
I've also merged #494 so this is going to be 5.1. I'll update the form builder too (probably tomorrow or Friday) so we can orchestrate releases.

@misaka if this is blocking anything we can release 5.1b1 in the meantime

**Pull request merged**
