### PR TITLE
Align documentation site with other X-GOVUK projects

### PR DESCRIPTION
**Pull request by paulrobertlloyd**
Possibly some controversial suggestions in this PR, but all up for debate (not just for this project, but others linked from the X-GOVUK website, too).

### 1. Licence and copyright

↳ Fixed in #431

* Removed Open Government Licence as not relevant or applicable in this context, and instead link to MIT Licence in repository.
* Added copyright notice against X-GOVUK.

Only changed in documentation footer, but wondering if corresponding changes need to be made in the `LICENCE` file also. Is this project covered by Crown Copyright? Is copyright held by DfE? Can it be transferred by updating a text file!? Unsure.

### 2. Project name

↳ Fixed in #432

* Added X-GOVUK logo
* Changed GOV.UK to X-GOVUK
* Changed name to Components for Ruby on Rails

What is the correct, canonical name for this project? It seems to vary. Separately, been struggling with many of our projects being called ‘GOV.UK [Project name]’ but appearing on documentation site headers as ‘X-GOVUK [Project name]’. Not quite sure how to resolve that tension.

### 3. Typeface

* Changed to using `system-ui, sans-serif`

This means loading less assets for one, but also looks different enough from GOV.UK to prevent confusion.

I know you purchased the font to get around GDS Transport licensing and usage restrictions, but its not _quite_ the same, and as mentioned, it currently renders incorrectly in Safari, though now fixed in Safari v17.

`system-ui` looks great on a Mac (uses SF Text), but honestly not as nice on Windows 10 from my experience (though nothing looks good there) and not sure which fonts will get used on different Linux distros.

Thought it might be possible to use Transport for examples only, but given the way GOV.UK Frontend works, almost impossible to override, or at least not easily.

### 4. Breadcrumbs

* Added breadcrumb in the home page masthead linking back to the main X-GOVUK website.

This is modelled on the GOV.UK SaaS services which do similar by linking back to a landing page on the [GOV.UK Service Manual](https://www.gov.uk/service-toolkit#gov-uk-services).

FWIW, this link is broken as the `shared-projects` anchor is missing on the X-GOVUK website since the heading was changed to ‘Projects’. Maybe the link should say ‘X-GOVUK Projects’?

Also added this to interior pages… though I’m kinda wondering if breadcrumbs are needed here? Also, while the GOV.UK SaaS websites include the page title in the breadcrumb, that’s not usually how breadcrumbs are used across GOV.UK.

***

Come to think of it, there are a few questions and issues here that cut across X-GOVUK. I wonder if we should use GitHub discussions feature somewhere in this organisation to discuss such topics, openly and with a bit more visibility? /cc @frankieroberto

### CODE REVIEW

**Comment by peteryates** [comment]
I love it, thank you.

I agree the fonts look fine on macOS and GNOME (thanks [Cantarell]((https://cantarell.gnome.org/)) but noticeably worse on Windows, almost to the point where it's not clear it's meant to resemble the GOV.UK Design System.

> Thought it might be possible to use Transport for examples only, but given the way GOV.UK Frontend works, almost impossible to override, or at least not easily.

I spent longer than I care to admit trying to get this working last time around, it's a total faff.

**Comment by paulrobertlloyd** [comment]
Huh, I was expecting more push back ☺️

Think I’ll create a separate PR for all licence-related work, and possibly a second PR to ensure the project name is consistent across different things. @peteryates; am assuming ‘GOV.UK Components for Ruby on Rails’ is the full title, with ‘GOV.UK Components’ the shorter version?

Once those are merged I’ll rebase this and update. Also need to update the icons/opengraph images, as well.

And then I can make the same changes to the form builder…!

**Comment by peteryates** [comment]
Yeah - that sounds good. I don't think I've been consistent in the past, but the 'short version' is usually GOV.UK Components or govuk-components. I'm happy with 'GOV.UK Components for Ruby on Rails' as the full title, descriptive and succinct 👍🏽

**Comment by paulrobertlloyd** [comment]
One final change was to add a revised homepage illustration, its corresponding Open Graph image, and pointing to X-GOVUK icons in place of GOV.UK ones.

**Comment by frankieroberto** [comment]
Slight downside with the longer name is that the breadcrumb drops to 2 lines on mobile (for me at least). Maybe change “X-GOVUK projects” to just “X-GOVUK”?

**Comment by paulrobertlloyd** [comment]
> Slight downside with the longer name is that the breadcrumb drops to 2 lines on mobile (for me at least). Maybe change “X-GOVUK projects” to just “X-GOVUK”?

Or maybe used short the shorter project name in the breadcrumb?

**Review by peteryates — APPROVED** [review]
Looks great, thank you @paulrobertlloyd 🙂

**Comment by paulrobertlloyd** [comment]
What are merge queues? That’s a new one to me!

**Comment by peteryates** [comment]
Merge queues are a handy feature where if you have a load of PRs waiting to be merged, you can queue them and GitHub will merge them sequentially (ensuring main keeps working throughout).

Not really necessary in this repo but I was learning about how they work and left it on.

**Pull request merged**
